"""Write the Windows version resource that PyInstaller stamps into the .exe.

Without this the executable ships with every version field blank - no company,
no product, no description, no version number. That matters beyond tidiness:
SmartScreen and most antivirus heuristics treat an unsigned binary carrying no
version resource at all as a strong signal, because that is exactly what a
freshly compiled dropper looks like. A real program says what it is.

It does not make the warning go away on its own - only an Authenticode
signature does that - but it removes one of the reasons for it, and it costs
nothing.

Generated rather than committed so the numbers can't drift from
romsrx.__version__, which is the one place a release bumps.

    python tools/version_info.py build/version-info.txt
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from romsrx import REPO, __version__  # noqa: E402

# The resource wants exactly four numbers; a version of "0.3.4" supplies three.
parts = [int(p) for p in __version__.split(".") if p.isdigit()][:4]
VERSION = tuple(parts + [0] * (4 - len(parts)))
OWNER = REPO.split("/")[0]

TEMPLATE = """\
# Generated by tools/version_info.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version},
    prodvers={version},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      # 0409 = en-US, 04B0 = Unicode.
      StringTable('040904B0', [
        StringStruct('CompanyName', '{owner}'),
        StringStruct('FileDescription', 'RomSrx - search and download ROM '
                                        'collections hosted on archive.org'),
        StringStruct('FileVersion', '{dotted}'),
        StringStruct('InternalName', 'RomSrx'),
        StringStruct('OriginalFilename', 'RomSrx.exe'),
        StringStruct('ProductName', 'RomSrx'),
        StringStruct('ProductVersion', '{dotted}'),
        StringStruct('LegalCopyright', 'Open source - https://github.com/{repo}'),
      ]),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def main() -> None:
    out = Path(sys.argv[1] if len(sys.argv) > 1 else "build/version-info.txt")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        TEMPLATE.format(version=VERSION, dotted=__version__,
                        owner=OWNER, repo=REPO),
        encoding="utf-8",
    )
    print(f"Wrote {out} for RomSrx {__version__}")


if __name__ == "__main__":
    main()
